#!/usr/bin/bash

images_path=~/Pictures/wallpapers/ 
colors=(gradient1.jpg gradient2.jpg gradient3.jpg gradient4.jpg)
number=$(($RANDOM % 4))
image=${colors[$number]}
wallpaper=$images_path$image
swww_fork=~/.config/hypr/scripts/tools/swww
$swww_fork init
$swww_fork img $wallpaper --transition-type grow --transition-pos 0.9,0.1 --transition-duration 2
