#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# waybar
$scripts/launch_waybar &
$scripts/tools/dynamic &

# wallpaper
swww kill
swww init
swww img ~/Pictures/wallpapers/gradient4.jpg &

# effects

# other
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
